// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8lJfPQ7HkqNiI0CqoG4Np0q4SlyZfoMI',
    appId: '1:396951276881:android:a687831b47b8112575d770',
    messagingSenderId: '396951276881',
    projectId: 'chatappagora-c867d',
    storageBucket: 'chatappagora-c867d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBedgig_8LKZqZ49U7Y93vnpKVZtTnxQxs',
    appId: '1:396951276881:ios:cfb554c578396bd275d770',
    messagingSenderId: '396951276881',
    projectId: 'chatappagora-c867d',
    storageBucket: 'chatappagora-c867d.firebasestorage.app',
    androidClientId: '396951276881-ie9qcc10r38rl3surf4g895libusurio.apps.googleusercontent.com',
    iosClientId: '396951276881-r80m3mm70ecchggvclcfsh3juh244umq.apps.googleusercontent.com',
    iosBundleId: 'com.demo.demoarchi',
  );
}
